### PR TITLE
[DIT22-53] Ryan/edit csv parser

### PR DESCRIPTION
**Pull request by ryannath**
[issue](https://digisoc.atlassian.net/browse/DIT22-53)

### CODE REVIEW

**Comment by ryannath** [comment]
@axieax why does it have the old commit? Is this what happen when you use rebase rather than just merging?

**Comment by axieax** [comment]
> @axieax why does it have the old commit? Is this what happen when you use rebase rather than just merging?

Your branch is out of date compared to the main branch because the hash of the commit is different. Update this current branch with a `git rebase main` from `ryan/edit_csv_parser` (make sure to Git pull first)

**Review by axieax — CHANGES_REQUESTED** [review]
LGTM, please fix up ^ first

**Comment by ryannath** [comment]
@axieax done, tht wasn't fun

**Review by axieax — APPROVED** [review]

**Comment by axieax** [comment]
Ahaha nice :))

**Pull request merged**
